version: '3.8'
services:
  opencv-tensorrt-dev: 
    profiles: ["build-only"]
    build:
      context: ./build/dependencies/Docker-OpenCV-TensorRT-Dev/build
      args:
        UBUNTU_IMAGE_VERSION: ${UBUNTU_IMAGE_VERSION}
        CUDA_VERSION: ${CUDA_VERSION}
        TENSORRT_VERSION: ${TENSORRT_VERSION}
        CUDA_ARCH_BIN: ${CUDA_ARCH_BIN}
        OPENCV_VERSION: ${OPENCV_VERSION}
        UID: ${UID}
        GID: ${GID}
        CMAKE_VERSION: ${CMAKE_VERSION}
        CPP_OPTIMIZATIONS: ${CPP_OPTIMIZATIONS}
    image: my/${TAG1}

  flir-opencv-tensorrt-dev:
    build:
      context: ./build
      args:
        BASE_IMAGE: ${BASE_IMAGE}
        FLIR_CAMERA_COUNT: ${FLIR_CAMERA_COUNT}
        FLIR_GID: ${FLIR_GID}
        CONTAINER_NAME: ${TAG2}

    image: my/${TAG2}

    network_mode: host
    command: tail -f /dev/null
    tty: true
    runtime: nvidia
  
    environment:
      DISPLAY: "${DISPLAY}"
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
      TERM: xterm-256color
      DEBUG_COLORS: "true"
      COLORTERM: truecolor
      ROS_MASTER_URI: "http://${ROS_MASTER_URI}:11311"
      ROS_IP: "${ROS_IP}"
      SSH_AUTH_SOCK: /ssh-agent
    volumes: 
      - ./:/home/docker/workspace
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - $SSH_AUTH_SOCK:/ssh-agent  # Forward SSH socket

    devices:
      - /dev/bus/usb:/dev/bus/usb
    
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, video, compute, utility]