version: '3.8'
services:
  flir-ros:
    build:
      context: ./build
      args:
        UID: ${UID}
        GID: ${GID}
        BASE_IMAGE: ${BASE_IMAGE}
        CMAKE_VERSION: ${CMAKE_VERSION}
        OPENCV_VERSION: ${OPENCV_VERSION}
        CPP_OPTIMIZATIONS: ${CPP_OPTIMIZATIONS}
        FLIR_CAMERA_SERIAL_NUMBERS: ${FLIR_CAMERA_SERIAL_NUMBERS}
        FLIR_CAMERA_COUNT: ${FLIR_CAMERA_COUNT}
        FLIR_MASTER_CAM_SERIAL: ${FLIR_MASTER_CAM_SERIAL}
        FLIR_TOP_CAM_SERIAL: ${FLIR_TOP_CAM_SERIAL}
        FLIR_MASTER_LINE: ${FLIR_MASTER_LINE}
        FLIR_SLAVE_LINE: ${FLIR_SLAVE_LINE}
        FLIR_GID: ${FLIR_GID}
        CONTAINER_NAME: ${TAG2}

    image: my/${TAG2}

    network_mode: host
    # command: tail -f /dev/null
    command: roslaunch flir_ros_cam interface.launch
    tty: true
  
    environment:
      DISPLAY: "${DISPLAY}"
      TERM: xterm-256color
      DEBUG_COLORS: "true"
      COLORTERM: truecolor
      ROS_MASTER_URI: "http://${ROS_MASTER_URI}:11311"
      ROS_IP: "${ROS_IP}"
      SSH_AUTH_SOCK: /ssh-agent
    volumes: 
      - ./:/home/docker/workspace
      - /etc/timezone:/etc/timezone:ro
      - $SSH_AUTH_SOCK:/ssh-agent  # Forward SSH socket

    devices:
      - /dev/bus/usb:/dev/bus/usb
    