// autogenerated file, do not edit

#pragma once

#include <string>

constexpr std::string_view CONFIG_DIR = "/home/docker/workspace/workspace/src/flir_ros_cam/cfg";

constexpr std::string_view TOPIC_IMAGES = "images";

constexpr int COMPRESSION_QUALITY = 50;
